version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/posts_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - seed
    command: npm run dev
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Seed service
  seed:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/posts_db
    command: >
      sh -c "until nc -z mongo 27017; do
        echo 'Waiting for MongoDB to start...'
        sleep 1
      done
      && echo 'MongoDB is up - executing seed script'
      && node scripts/seed.js"
    restart: "no"

volumes:
  mongo_data: